name: Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checking out the repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Setting up Git user
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_config_global: true
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  git_tag_gpgsign: true

            - name: Setting up PNPM
              uses: pnpm/action-setup@v2

            - name: Setting up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'pnpm'

            - name: Installing Node.js dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm install --frozen-lockfile

            - name: Retrieving node_modules cache
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules/.cache
                  key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
                  restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

            - name: Creating release pull request
              uses: changesets/action@v1
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
              with:
                  setupGitUser: false
                  commit: 'build(release): bump vesion'
                  title: 'build(release): bump vesion'
                  version: pnpm run ci:version
                  publish: pnpm run ci:publish
