name: Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checking out the repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Setting up Git user
              uses: crazy-max/ghaction-import-gpg@v4
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  git_config_global: true
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  git_tag_gpgsign: true
                  git_committer_name: 'jpapini'
                  git_committer_email: 'julien.papini@gmail.com'

            - name: Setting up PNPM
              uses: pnpm/action-setup@v2

            - name: Setting up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'pnpm'

            - name: Installing Node.js dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm install --frozen-lockfile

            - name: Creating release pull request
              uses: changesets/action@v1
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  setupGitUser: false
                  commit: 'chore(release): bump vesion'
                  title: 'chore(release): bump vesion'
                  version: pnpm ci:version
                  publish: pnpm ci:publish
